In [5]:
import numpy as np


array([1, 2, 3])

 Basics


In [7]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
# 2D array of floats
b=np.array([[6.6,5.5,4.3],[2,4,3],[4,7.6,9]])
print(b)
            

[[6.6 5.5 4.3]
 [2.  4.  3. ]
 [4.  7.6 9. ]]


In [11]:
# get dimensions
print(a.ndim)
print(b.ndim)

1
2


In [12]:
# get shape
print(a.shape)
print(b.shape)

(3,)
(3, 3)


In [13]:
# get data type
print(a.dtype)
print(b.dtype)

int32
float64


In [17]:
# get size
print(a.itemsize)
print(b.itemsize)


4
8


In [18]:
# get total size
print(a.nbytes)
print(b.nbytes)

12
72
