In [1]:
import numpy as np

a=np.array([1,3,5,7,9])
print(a)

[1 3 5 7 9]


In [2]:
a+2

array([ 3,  5,  7,  9, 11])

In [3]:
a-2

array([-1,  1,  3,  5,  7])

In [4]:
a*2

array([ 2,  6, 10, 14, 18])

In [6]:
b=np.array([2,4,6,8,10])
a+b

array([ 3,  7, 11, 15, 19])

In [7]:
# take sin of all values
np.sin(a)

array([ 0.84147098,  0.14112001, -0.95892427,  0.6569866 ,  0.41211849])