In [6]:
import numpy as np

In [5]:
a=np.array([[1,2,3,4,5,6,7],[2,3,4,5,6,7,8]])
print(a)

[[1 2 3 4 5 6 7]
 [2 3 4 5 6 7 8]]


In [5]:
# get a specific element
print(a[1,5])

7


In [7]:
# get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [9]:
# get a specific column
print(a[:,2])

[3 4]


In [4]:
# [startIndex,EndIndex,stepsize]
print(a[0,1:6:3])

[2 5]


In [8]:
# editing the array elements
a[1,3]=6
print(a)

[[1 2 3 4 5 6 7]
 [2 3 4 6 6 7 8]]


In [9]:
a[:,3]=6
print(a)

[[1 2 3 6 5 6 7]
 [2 3 4 6 6 7 8]]
