In [7]:
import numpy as np
# all zeros 2D matrix
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
# all zeros 1D matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
# all 1's matrix
np.ones((4,2),dtype='int')

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [12]:
# any other number
np.full((2,2),44,dtype='float')

array([[44., 44.],
       [44., 44.]])

In [14]:
# random decimal numbers
np.random.rand(3,4)

array([[0.75830691, 0.12506236, 0.36869671, 0.49392875],
       [0.93348015, 0.75235563, 0.73476312, 0.91917657],
       [0.52127381, 0.34561644, 0.26327843, 0.96027017]])

In [18]:
# random integer values
np.random.randint(-1,2,size=(3,3))

array([[ 1, -1,  0],
       [ 0, -1,  0],
       [-1,  0,  0]])

In [20]:
# identity matrix
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
arr=np.array([[1,4,7]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 4 7]
 [1 4 7]
 [1 4 7]]


In [34]:
output=np.ones((5,5),dtype='int')
print(output)
z=np.zeros((3,3))

z[1,1]=9
print(z)
output[1:-1,1:-1]=z
print(output)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [36]:
a=np.array([1,6,9])
b=a
print(a)
b[1]=100
print(a)
print(b) 
# both point to same reference therefore values in both arrays will be changed

b=a.copy()
b[0]=200
print(a)
print(b) 

[1 6 9]
[  1 100   9]
[  1 100   9]
[  1 100   9]
[200 100   9]
