In [1]:
import numpy as np
filedata=np.genfromtxt('data.txt',delimiter=',')
filedata.astype('int32')
filedata

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [3]:
filedata>10

array([[False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [5]:
filedata[filedata>14].astype('int32')

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [8]:
np.all(filedata>9,axis=0)

array([False, False, False, False, False, False, False, False, False,
        True])

In [9]:
np.all(filedata>9,axis=1)

array([False,  True,  True])

In [12]:
(filedata>10) & (filedata<20)

array([[False, False, False, False, False, False, False, False, False,
        False],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [13]:
(~(filedata>10) & (filedata<20))

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])