In [11]:
import numpy as np
before=np.array([[1,2],[4,5],[7,8],[3,6]])
before

array([[1, 2],
       [4, 5],
       [7, 8],
       [3, 6]])

In [12]:
print(before.shape)

(4, 2)


In [13]:
# reorganizing arrays
after=before.reshape((2,4))
print(after)


[[1 2 4 5]
 [7 8 3 6]]


In [14]:
after=before.reshape((2,2,2))
print(after)

[[[1 2]
  [4 5]]

 [[7 8]
  [3 6]]]


In [19]:
# vertical stacking vectors
v1=np.array([1,2,3])
v2=np.array([4,5,6])
v3=np.array([2,5,8])
v4=np.array([5,8,7])
np.vstack([v1,v2])

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.vstack([v1,v2,v3,v4])

array([[1, 2, 3],
       [4, 5, 6],
       [2, 5, 8],
       [5, 8, 7]])

In [21]:
# horizontal stack
np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6])